---
project_name: cf-sample-plugin

builds:
  - id: plugin
    binary: cf-sample-plugin
    dir: .
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s
      - -w
      - -X main.version={{.Version}}
      - -X main.commit={{.FullCommit}}
      - -X main.branch={{.Branch}}
      - -X main.buildUser={{.Env.USER}}
      - -X main.buildDate={{.Date}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: archives
    builds:
      - plugin
    format: "tar.gz"
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    wrap_in_directory: true
    files:
      - LICENSE*
      - README*
      - manifest.yml

  - id: plugin
    format: binary
    builds: [ plugin ]
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt
  algorithm: sha256

release:
  github:
    owner: gmllt-samples
    name: cf-sample-plugin
  prerelease: auto
  name_template: '{{.Tag}}'

changelog:
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
